# Generated by Django 3.1.1 on 2020-09-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='bunq_api_environment',
            field=models.CharField(choices=[('SANDBOX', 'SANDBOX'), ('PRODUCTION', 'PRODUCTION')], default='SANDBOX', max_length=30),
        ),
    ]
