# Generated by Django 3.1.1 on 2020-09-13 17:34

from django.db import migrations, models
import localflavor.generic.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_monetaryaccounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monetaryaccounts',
            name='iban',
            field=localflavor.generic.models.IBANField(include_countries=None, max_length=34, unique=True, use_nordea_extensions=False),
        ),
        migrations.AlterField(
            model_name='monetaryaccounts',
            name='monetary_account_id',
            field=models.IntegerField(unique=True),
        ),
    ]
