# Generated by Django 3.1.1 on 2020-09-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20200913_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='monetaryaccounts',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
